name: ProTrader5 CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: protrader5
  KUBE_NAMESPACE: protrader5

jobs:
  # Job 1: Lint and Test Backend Services
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - user-service
          - trading-service
          - copy-trading-service
          - algo-trading-service
          - charting-service
          - risk-management-service
          - notification-service
          - payment-service
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/services/${{ matrix.service }}/package-lock.json

      - name: Install dependencies
        working-directory: backend/services/${{ matrix.service }}
        run: npm ci

      - name: Run linter
        working-directory: backend/services/${{ matrix.service }}
        run: npm run lint

      - name: Run unit tests
        working-directory: backend/services/${{ matrix.service }}
        run: npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: backend/services/${{ matrix.service }}/coverage/lcov.info
          flags: ${{ matrix.service }}
          name: ${{ matrix.service }}-coverage

  # Job 2: Lint and Test Frontend
  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/web/package-lock.json

      - name: Install dependencies
        working-directory: frontend/web
        run: npm ci

      - name: Run linter
        working-directory: frontend/web
        run: npm run lint

      - name: Run unit tests
        working-directory: frontend/web
        run: npm run test:coverage

      - name: Build frontend
        working-directory: frontend/web
        run: npm run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: frontend/web/coverage/lcov.info
          flags: frontend
          name: frontend-coverage

  # Job 3: Security Scanning
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high

  # Job 4: Build and Push Docker Images
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test, security-scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    strategy:
      matrix:
        service:
          - user-service
          - trading-service
          - copy-trading-service
          - algo-trading-service
          - charting-service
          - risk-management-service
          - notification-service
          - payment-service
          - websocket-server
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/services/${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ matrix.service }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ matrix.service }}:buildcache,mode=max

  # Job 5: Build and Push Frontend
  build-frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-latest
    needs: [frontend-test, security-scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/web-app
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/web
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/web-app:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/web-app:buildcache,mode=max

  # Job 6: Deploy to Kubernetes
  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: [build-and-push, build-frontend]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name protrader5-cluster --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          # Update image tags in deployments
          kubectl set image deployment/user-service user-service=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/user-service:master-${{ github.sha }} -n ${{ env.KUBE_NAMESPACE }}
          kubectl set image deployment/trading-service trading-service=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/trading-service:master-${{ github.sha }} -n ${{ env.KUBE_NAMESPACE }}
          kubectl set image deployment/copy-trading-service copy-trading-service=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/copy-trading-service:master-${{ github.sha }} -n ${{ env.KUBE_NAMESPACE }}
          kubectl set image deployment/algo-trading-service algo-trading-service=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/algo-trading-service:master-${{ github.sha }} -n ${{ env.KUBE_NAMESPACE }}
          kubectl set image deployment/charting-service charting-service=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/charting-service:master-${{ github.sha }} -n ${{ env.KUBE_NAMESPACE }}
          kubectl set image deployment/risk-management-service risk-management-service=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/risk-management-service:master-${{ github.sha }} -n ${{ env.KUBE_NAMESPACE }}
          kubectl set image deployment/notification-service notification-service=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/notification-service:master-${{ github.sha }} -n ${{ env.KUBE_NAMESPACE }}
          kubectl set image deployment/payment-service payment-service=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/payment-service:master-${{ github.sha }} -n ${{ env.KUBE_NAMESPACE }}
          kubectl set image deployment/websocket-server websocket-server=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/websocket-server:master-${{ github.sha }} -n ${{ env.KUBE_NAMESPACE }}
          kubectl set image deployment/web-app web-app=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/web-app:master-${{ github.sha }} -n ${{ env.KUBE_NAMESPACE }}

      - name: Wait for rollout to complete
        run: |
          kubectl rollout status deployment/user-service -n ${{ env.KUBE_NAMESPACE }} --timeout=5m
          kubectl rollout status deployment/trading-service -n ${{ env.KUBE_NAMESPACE }} --timeout=5m
          kubectl rollout status deployment/copy-trading-service -n ${{ env.KUBE_NAMESPACE }} --timeout=5m
          kubectl rollout status deployment/algo-trading-service -n ${{ env.KUBE_NAMESPACE }} --timeout=5m
          kubectl rollout status deployment/charting-service -n ${{ env.KUBE_NAMESPACE }} --timeout=5m
          kubectl rollout status deployment/risk-management-service -n ${{ env.KUBE_NAMESPACE }} --timeout=5m
          kubectl rollout status deployment/notification-service -n ${{ env.KUBE_NAMESPACE }} --timeout=5m
          kubectl rollout status deployment/payment-service -n ${{ env.KUBE_NAMESPACE }} --timeout=5m
          kubectl rollout status deployment/websocket-server -n ${{ env.KUBE_NAMESPACE }} --timeout=5m
          kubectl rollout status deployment/web-app -n ${{ env.KUBE_NAMESPACE }} --timeout=5m

      - name: Verify deployment
        run: |
          kubectl get pods -n ${{ env.KUBE_NAMESPACE }}
          kubectl get services -n ${{ env.KUBE_NAMESPACE }}

  # Job 7: Run Smoke Tests
  smoke-tests:
    name: Run Smoke Tests
    runs-on: ubuntu-latest
    needs: deploy-to-kubernetes
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: testing/smoke-tests
        run: npm ci

      - name: Run smoke tests
        working-directory: testing/smoke-tests
        run: npm run test
        env:
          API_URL: https://api.protrader5.com
          WEB_URL: https://protrader5.com

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: smoke-test-results
          path: testing/smoke-tests/results/

  # Job 8: Notify Deployment
  notify-deployment:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: smoke-tests
    if: always()
    
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            Deployment Status: ${{ job.status }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Message: ${{ github.event.head_commit.message }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ProTrader5 Deployment ${{ job.status }}
          to: devops@protrader5.com
          from: ci-cd@protrader5.com
          body: |
            Deployment Status: ${{ job.status }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Message: ${{ github.event.head_commit.message }}
            
            View details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        if: always()
